### ISSUE TITLE
bootstrap.signed

### ISSUE THREAD

**Issue by trever001** [oxen-io/lokinet#1697]
how to create a bootstrap.signed file with my loki testnode

**Comment by majestrate** [comment]
lokinet will generate one called self.signed, you just need to upload
it to a webserver and call it bootstrap.signed. 
you can make your lokinet router run as a seed node by using a config
option in [bootstrap] section, seed-node=true
this will let it run without any bootstrap nodes

**Comment by trever001** [comment]
how my lokid testnet connect with lokinet by which way

**Comment by jagerman** [comment]
What are you trying to run?  Normally service nodes (testnet or mainnet) are required to have public IPs.  The default packaging for Debian and Ubuntu set this up (including downloading a testnet and mainnet bootstrap.signed file); mainnet starts by default (systemd services `oxen-node.service`, `oxen-storage-server.service`, and `lokinet-router.service`) but if you want to run testnet you can `sudo systemctl disable --now oxen-node oxen-storage-server lokinet-router` for each of those and then `sudo systemctl enable --now oxen-testnet-node oxen-testnet-storage-server lokinet-testnet-router` to start up the testnet versions.

If all you want is to access lokinet (rather than running a network node) then you don't need this setup at all.

(Also note that testnet is a completely different network meant just for testing with basically just test traffic rather than real routing traffic).

**Comment by trever001** [comment]
~/lokinet/lokinet/build$ lokinet -r
[NFO] [lokinet](674) 2021-07-09 18:00:04.706 GMT [+0.002s] llarp/config/config.cpp:1319	Attempting to create config file for router at "/home/user/.lokinet/lokinet.ini"
[NFO] [lokinet](674) 2021-07-09 18:00:04.707 GMT [+0.003s] llarp/config/config.cpp:1340	Generated new config "/home/user/.lokinet/lokinet.ini"
[NFO] [lokinet](496) 2021-07-09 18:00:04.707 GMT [+0.003s] daemon/lokinet.cpp:264	Using config file: "/home/user/.lokinet/lokinet.ini"
[NFO] [lokinet](496) 2021-07-09 18:00:04.707 GMT [+0.003s] llarp/context.cpp:64	lokinet-0.9.5-4f1bd14d (dev build)
[NFO] [lokinet](496) 2021-07-09 18:00:04.707 GMT [+0.003s] llarp/context.cpp:65	starting up
isservicenode() : 1
[NFO] [lokinet](496) 2021-07-09 18:00:04.708 GMT [+0.004s] llarp/rpc/lokid_rpc_client.cpp:60	connecting to lokid via LMQ at tcp://:0
[ERR] [lokinet](496) 2021-07-09 18:00:04.708 GMT [+0.004s] llarp/router_contact.cpp:569	Failed to open "/home/user/.lokinet/self.signed"
[NFO] [lokinet](496) 2021-07-09 18:00:04.708 GMT [+0.004s] llarp/config/key_manager.cpp:190	Generating new key"/home/user/.lokinet/encryption.key"
[NFO] [lokinet](496) 2021-07-09 18:00:04.709 GMT [+0.005s] llarp/config/key_manager.cpp:190	Generating new key"/home/user/.lokinet/transport.key"
[ERR] [lokinet](496) 2021-07-09 18:00:04.709 GMT [+0.005s] llarp/router/router.cpp:521	No bootstrap files specified in config file, and the default
[ERR] [lokinet](496) 2021-07-09 18:00:04.709 GMT [+0.005s] llarp/router/router.cpp:522	bootstrap file "/home/user/.lokinet/bootstrap.signed" does not exist.
[ERR] [lokinet](496) 2021-07-09 18:00:04.709 GMT [+0.005s] llarp/router/router.cpp:523	Please provide a bootstrap file (e.g. run 'lokinet-bootstrap)'
[ERR] [lokinet](496) 2021-07-09 18:00:04.709 GMT [+0.005s] daemon/lokinet.cpp:293	Fatal: caught exception while running: No bootstrap files available.

**Comment by jagerman** [comment]
You need to run `lokinet-bootstrap`
