### ISSUE TITLE
ngtcp2 stuff & shared build incompat

### ISSUE THREAD

**Issue by cathugger** [oxen-io/lokinet#1744]
**Describe the bug**
lokinet built in shared mode doesn't install ngtcp2 related libs and thus fails to run as it fails to find relevant .so
i worked this around in archlinux aur pkgbuild by pulling in ngtcp2 dependency, but recently it started failing as apparently upstream have changed something around and removed some functions and thus lokinet fails to start because symbols are missing

**To Reproduce**
build stuff as in https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=lokinet

**Screenshots Or Logs**
`/usr/bin/lokinet: symbol lookup error: /usr/bin/lokinet: undefined symbol: ngtcp2_conn_client_new`

**Device and Operating system (please complete the following information):**
 - OS: arch btw
-  Device: pc
 - Lokinet Version number or Git commit hash: 0.9.5

**Comment by cathugger** [comment]
solution would probably be linking ngtcp2 as .a but idk how hard thats to do.
or bumping currently used ngtcp2, adopting relevant code to recent changes, then allowing actually using system's ngtcp2 as opposed to vendored one.

**Comment by fyrak1s** [comment]
After fixing #1745 manually, I am now stuck on this issue too (trying to compile 0.9.6).
```
lokinet: error while loading shared libraries: libngtcp2.so.0: cannot open shared object file: No such file or director
```

A fix would be appreciated. IMO an option to use ngtcp2 as a shared lib would be nice.

**Comment by majestrate** [comment]
> A fix would be appreciated. IMO an option to use ngtcp2 as a shared lib would be nice.

the problem is actually that ngtcp2 *is* being used as a shared library and it's not supposed to.

**Comment by jagerman** [comment]
> A fix would be appreciated. IMO an option to use ngtcp2 as a shared lib would be nice.

Long term I agree, but currently ngtcp2 is not properly versioned at all, doesn't installs pkgconfig files, and there's no realistic way we can check the minimum required version for making sure we can safely link to it (because it also breaks APIs sometimes).  All of this makes it very, very difficult to do this generically.  Now if it were packaged in a distribution, the distribution would have some versioning -- perhaps the git date -- and thus there would be something the *distribution* package could rely on to link to the shared library, but that's a different matter.

Edit: Its cmake packaging is also rather nasty: take a look at the mess we have to do in cmake/ngtcp2_lib.cmake to build the damn thing.  It's a powerful library, but I think its author has never published a public library before.

**Comment by fyrak1s** [comment]
I have tried to backport the patch to release 0.9.6 (I have copied over cmake/ngtcp2_lib.cmake since it did not exist at all), but I am still getting the same error.

I guess some other patches need to be applied too. Then I tried to compile startight from git but I got
```
fatal error: zmq.hpp: No such file or directory
```
during compilation.

So not sure what to do, I would still like to packaged lokinet for my distro, but either I need a full fix backported to 0.9.6, or resolve the new issue :)
Also I'd rather package a stable release than straight form git.

**Comment by jagerman** [comment]
> fatal error: zmq.hpp: No such file or directory

You need a build dependency on the cppzmq package (naming and location may vary, depending on the distribution).  However, proper packaging will want you to package oxen-mq first, and build-dep Lokinet onto that, rather than embedding it into the lokinet package.

**Comment by majestrate** [comment]
for aur package you need to depend on https://aur.archlinux.org/packages/cppzmq/

**Comment by fyrak1s** [comment]
Thank you both.

I have packaged and installed cppzmq and now the compilation goes about correctly.
But the installation step fails with
```
...
-- Installing: /Programs/Lokinet/20211007-GIT/include/oxenmq/version.h
CMake Error at external/oxen-mq/cmake_install.cmake:92 (file):
  file INSTALL cannot find
  "/Data/Compile/Sources/lokinet-dev/external/oxen-mq/cppzmq/zmq.hpp": No
  such file or directory.
Call Stack (most recent call first):
  cmake_install.cmake:42 (include)
```

Does it even need to copy that file over if cppzmq is already installed on the system as a shared lib?

**Comment by majestrate** [comment]
looks like it is trying to do a static deps build

**Comment by fyrak1s** [comment]
> looks like it is trying to do a static deps build


Those are my cmake options:
```
        -DCMAKE_BUILD_TYPE=Release
        -DCMAKE_C_FLAGS="$CFLAGS"
        -DCMAKE_CXX_FLAGS="$CXXFLAGS"
        -DNATIVE_BUILD=OFF
        -DUSE_NETNS=OFF
        -DUSE_AVX2=OFF
        -DXSAN=OFF
        -DWITH_TESTS=OFF
        -DDOWNLOAD_SODIUM=OFF
        -DSUBMODULE_CHECK=OFF
        -DWITH_SYSTEMD=OFF
        -DFORCE_OXENMQ_SUBMODULE=ON
        -DBUILD_SHARED_LIBS=ON
        -DBUILD_STATIC_DEPS=OFF
        -Wno-dev
```

Does that look alright? (I am building oxenmq inbuild for now)

**Comment by majestrate** [comment]
looks fine

**Comment by jagerman** [comment]
> Does it even need to copy that file over if cppzmq is already installed on the system as a shared lib?

No; try adding `-DOXENMQ_INSTALL_CPPZMQ=OFF` to your cmake options.

(The reason that defaults to ON is that many distributions included an ancient version of cppzmq until quite recently).

**Comment by jagerman** [comment]
You may also want to take a look at the `debian/rules` file (inside the `debian/sid` branch) to compare with the flags we use for Debian builds:

https://github.com/oxen-io/lokinet/blob/debian/sid/debian/rules

**Comment by fyrak1s** [comment]
> No; try adding -DOXENMQ_INSTALL_CPPZMQ=OFF to your cmake options.

Thank you that made it compile and install successfully :)

I would also like to build oxen-mq separately as you've suggested previously, but the oxen-mq readme (https://github.com/oxen-io/oxen-mq) does not mention which build or runtime dependencies it needs.

Would you be so nice to add such information?

**Comment by jagerman** [comment]
The only two dependencies oxenmq needs are zeromq >= 4.3 and libsodium >= 1.0.18.
