### ISSUE TITLE
Error upon running lokinet-bootstrap

### ISSUE THREAD

**Issue by fyrak1s** [oxen-io/lokinet#1765]
After successully resolving https://github.com/oxen-io/lokinet/issues/1744 I was able to run `lokinet -g`.

But running `lokinet-bootstrap` gave me the following error:
```
$ lokinet-bootstrap                                                                               
fetching https://seed.lokinet.org/lokinet.signed
failed to fetch 'https://seed.lokinet.org/lokinet.signed' HTTP 0
```

If it helps, [here is a strace output](https://gist.github.com/Nuc1eoN/d0cba3f07b9d02da67f9832d292cdb55).

Lokinet Version: git

**Comment by lozzahax** [comment]
> After successully resolving #1744 I was able to run `lokinet -g`.
> 
> But running `lokinet-bootstrap` gave me the following error:
> 
> ```
> $ lokinet-bootstrap                                                                               
> fetching https://seed.lokinet.org/lokinet.signed
> failed to fetch 'https://seed.lokinet.org/lokinet.signed' HTTP 
> ```
> 
> If it helps, [here is a strace output](https://gist.github.com/Nuc1eoN/d0cba3f07b9d02da67f9832d292cdb55).
> 
> Lokinet Version: git

Are you trying to fork lokinet? That only occur if you changed that address to yours or use sudo

**Comment by majestrate** [comment]
that error occurs when you statically compile libssl into lokinet-bootstrap, it can't find the ca bundle.

**Comment by lozzahax** [comment]
> that error occurs when you statically compile libssl into lokinet-bootstrap, it can't find the ca bundle.

Not only libssl, i had experience with that too during my forking stage

**Comment by jagerman** [comment]
> After successully resolving #1744 I was able to run lokinet -g.

Also worth noting: we've started bundling the bootstrap file into the package itself (for .deb packages starting from 0.9.6-2, and .rpm packages), so that installing lokinet doesn't have to download a bootstrap file before it can operate.  (We've also done this for a while for Windows/macOS).  I'd encourage you to do the same if packaging for another distro.  The file is added as `contrib/bootstrap/mainnet.signed` in `dev` (and so will be there for 0.9.7), and can be downloaded (e.g. with `wget`) from https://seed.lokinet.org/lokinet.signed.  (There's also one for testnet, if you are considering making a testnet service).

**Comment by quenero** [comment]
> > After successully resolving #1744 I was able to run lokinet -g.
> 
> Also worth noting: we've started bundling the bootstrap file into the package itself (for .deb packages starting from 0.9.6-2, and .rpm packages), so that installing lokinet doesn't have to download a bootstrap file before it can operate. (We've also done this for a while for Windows/macOS). I'd encourage you to do the same if packaging for another distro. The file is added as `contrib/bootstrap/mainnet.signed` in `dev` (and so will be there for 0.9.7), and can be downloaded (e.g. with `wget`) from https://seed.lokinet.org/lokinet.signed. (There's also one for testnet, if you are considering making a testnet service).

I need to follow up. I love the new implementation. That means lokinet-bootstrap will be removed?

**Comment by jagerman** [comment]
> That means lokinet-bootstrap will be removed?

No, not removed, just not necessary to be called anymore when you install the package (because the package itself installs the /var/lib/lokinet/bootstrap.signed).

You'd still need it if you are configuring/setting up lokinet yourself, or want to run it with a different bootstrap, or on a different network.

**Comment by fyrak1s** [comment]
> that error occurs when you statically compile libssl into lokinet-bootstrap, it can't find the ca bundle.

How can I disable that?

> Also worth noting: we've started bundling the bootstrap file into the package itself

Thank you I will also look into this!

**Comment by majestrate** [comment]
> > that error occurs when you statically compile libssl into lokinet-bootstrap, it can't find the ca bundle.
> 
> How can I disable that?

dont use a static libssl, link against the system's libssl.

**Comment by fyrak1s** [comment]
> dont use a static libssl, link against the system's libssl.

I am linking against the systems libssl (OpenSSL 1.x and 3.x both installed).

**Comment by majestrate** [comment]
it also requires your libssl to know where its ca-cert bundle is
