### ISSUE TITLE
error compile -> unused some vars

### ISSUE THREAD

**Issue by sh4m2hwz** [oxen-io/lokinet#1767]
/path/to/lokinet/external/oxen-mq/oxenmq/oxenmq.cpp:414:41: error: unused variable ‘busy’ [-Werror=unused-variable]
             for (auto& [run, busy, queue] : tagged_workers) {
                                         ^
and some more similar errors

please check oxenmq for busy and queue vars for unused

**Comment by majestrate** [comment]
On Wed, 2021-10-13 at 02:45 -0700, pr4gasm wrote:
> /media/veracrypt8/componets_rat/lokinet/external/oxen-
> mq/oxenmq/oxenmq.cpp:414:41: error: unused variable ‘busy’ [-
> Werror=unused-variable]
> for (auto& [run, busy, queue] : tagged_workers) {
> ^
> and some more similar errors
> please check oxenmq for busy and queue vars for unused
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub, or unsubscribe.

your compiler is too old.

**Comment by jagerman** [comment]
To clarify: those are warnings in gcc-8 that are fixed in gcc-9 and newer, which is why we haven't done anything about it.  I've submitted a PR to oxen-mq to allow this to be turned off (https://github.com/oxen-io/oxen-mq/pull/53), but currently you'll have to remove the `-Werror` option from `external/oxen-mq/CMakeLists.txt` to make it compile.
