### ISSUE TITLE
Lokinet on homebrew 👍🏻

### ISSUE THREAD

**Issue by 71337** [oxen-io/lokinet#1802]
Instead of anoying work with mac appstore (signing..) Why not creating like tor a lokinet homebrew package ?

**Comment by majestrate** [comment]
we tried that before a while ago and we were rejected for being too small of a project.
I doubt we will apply for inclusion in homebrew again when more reasonable solutions for compiling from source exist like macports.

**Comment by jagerman** [comment]
The bigger issue is that in order to set up the tunnel to have it work properly throughout the OS we need access to the special magic Apple APIs for packet tunneling, but you are only allowed to call those APIs if you are a signed, Apple-Mac-Store-sourced package.

**Comment by majestrate** [comment]
in theory we could support requiring root on macos just for homebrew/macports but the number of users that would want this is not enough to warrant the port. I would honestly rather just entirely drop support for all apple platforms given how much of a pain it has been doing it the idiomatic apple way.

**Comment by hexcowboy** [comment]
As an end user I would much prefer granting root privileges for a homebrew repo rather than installing something from the App Store.

**Comment by majestrate** [comment]
you are in a microscopic minority of end users. I do not want to contribute to your ecosystem.

**Comment by hexcowboy** [comment]
Oh I wasn't aware you have conducted user research and determined that I am a microscopic minority. I was just providing feedback. I also did not ask you to contribute to "my" (Apple's) ecosystem, so no need for the passive aggressiveness.

Also genuinely curious why would you prefer to distribute your app on a closed-source code-signed App Store if your views against Apple are so strong? Why do you think that's more idiomatic? Homebrew is open source, free, cross-platform, and easily available on all macOS systems. Seems like that would be a better choice for a privacy-centric networking protocol.

**Comment by majestrate** [comment]
Apple's developer ecosystem is almost intentionally designed to be hostile to developers who want users to be able to compile from source. I will not support that ecosystem and any users on it, I actually would rather fully drop support for all apple platforms but that isn't an option. If you find this disagreeable take it up with Apple, they constructed their ecosystem in this way, not us. I refuse to participate in Apple's farce of "supporting open source", we are honest with our support on Apple, it is non free and will NEVER be free on any of Apple's platforms, because of Apple's choices and code signing requirements. I refuse to pretend users in the Apple Walled garden can have any reasonable expectations of privacy, I will be open and transparent about their choices and how it impacts users. I wish it wasn't this way and Apple was in fact not actively hostile to their users and developers who want to compile from source but it do be that way.
I will not support your platform. Have a nice day.

**Comment by majestrate** [comment]
Homebrew required us to be a "notable" project and at the time of our previous application were were not. Now that we are above their arbitrary threshold of "notoriety" some time has passed and we have found macports far more suitable for our needs.

We use macports in our CI pipleine so if we ever do add support for source based distributions on apple it will be via macports.

**Comment by jagerman** [comment]
> Also genuinely curious why would you prefer to distribute your app on a closed-source code-signed App Store if your views against Apple are so strong? Why do you think that's more idiomatic? Homebrew is open source, free, cross-platform, and easily available on all macOS systems. Seems like that would be a better choice for a privacy-centric networking protocol.

Because supporting Homebrew isn't a realistic solution to "Lokinet supports macos".  We would *still* have to support Lokinet on macOS for regular (i.e. non-homebrew, non-macports, non-compile-everything-yourself) Mac users, where "Step 1. Install Homebrew" just isn't an option.  And so now we'd just have to support full macOS mode with all the signing BS *and* Homebrew on top of that, where homebrew would have to use a completely different, non-Apple-sanctioned set of hacks to set up networking.

If someone wants to package lokinet for Homebrew *include supporting changing DNS settings and network configuration* (because this is the really painful part with macOS) then we'd be happy to aid in making it work (such as accepting patches as upstream), but it isn't something we're interested in carrying *in addition* to full native macOS support.  The obstacle, though, is that as far as I can see, Apple refuses to allow things to reliably set up VPNs and change DNS settings, even if the process has root access, if it isn't signed and going through the App store.
