### ISSUE TITLE
Incorrectly setting DNS on lokitun0 on start

### ISSUE THREAD

**Issue by ple1n** [oxen-io/lokinet#1887]
**Describe the bug**

1. Start lokinet via systemctl 

2. 
![image](https://user-images.githubusercontent.com/68096727/162216613-e83ad236-9f2d-4654-bd42-14fb0c89d59e.png)

After starting lokinet, query the `exit.loki` and systemd-resolved sends DNS requests through lokitun0 to destination `127.3.2.1` which is rejected.

It could be my fault too, IDK

**Device and Operating system (please complete the following information):**
 - OS: Ubuntu 21.10, 5.13.0-37-generic
-  Device: PC
 - Lokinet Version number or Git commit hash: lokinet-0.9.8-deb0.9.8-1~ubuntu2110

**Comment by majestrate** [comment]
looking at this now i think that the `-DefaultRoute` flag may be the issue. the problem was the source address for dns queries was the interface address of `lokitun0` and that would cause issues when trying to query `127.3.2.1` using that source address. when doing packet capture are you snooping `lo` or `lokitun0` ?

**Comment by majestrate** [comment]
![2022-04-07-101431_799x1118_scrot](https://user-images.githubusercontent.com/499653/162219977-93e1ed2f-52e5-4b4d-80e6-5894ee85a15b.png)

I always run lokinet with an exit node on, so this is what mine looks like. the most noticeable deviation is `+DefaultRoute`.

**Comment by ple1n** [comment]
I didn't set an exit node in the config. Actually I'm trying to connect to the port 8888 proxy on exit.loki

Under the 'resolvectl` reverted case

![image](https://user-images.githubusercontent.com/68096727/162220802-8c14e960-5c61-498a-92bd-f9b300fd925d.png)
 
The queries were sent on all interfaces

**Comment by majestrate** [comment]
i see, we'll have to block snode and loki gtld explicitly on those other interfaces it seems.

**Comment by jagerman** [comment]
> The queries were sent on all interfaces

You specifically reverted the DNS setting that prevents this.

> i see, we'll have to block snode and loki gtld explicitly on those other interfaces it seems.

That's what our current `~loki ~snode` setting does.  He undid it.

What's not clear to me is why resolvectl is failing here.

**Comment by majestrate** [comment]
![image](https://user-images.githubusercontent.com/499653/162230621-177de561-33fa-4d45-824f-963c8b6e4e7f.png)
his original post from sogs

**Comment by jagerman** [comment]
So this issue is caused, apparently, by https://github.com/systemd/systemd/issues/20485 merged sometime between 247 and 249.  (@majestrate is on 247.3, and doesn't see it, while my router is on 250.3 and does).

As a workaround I can set `[dns] bind=127.0.0.1:953` in `/etc/loki/lokinet.ini` and that *does* work, because the systemd PR that merged the support special-cases local IPs and apparently recognizes 127.0.0.1 but not 127.3.2.1.  (*Both* of these feels like bugs in systemd-resolved).

**Comment by jagerman** [comment]
I think to work around the systemd issue (which we need to -- even if this gets fixed in upstream systemd, this is present in Ubuntu impish and will also likely be present for LTS duration in Ubuntu jammy) we'll need to:

- add an additional default DNS listener on 127.0.0.1:0 (i.e. random high port).  That is, the default setting would be equivalent to `[dns] bind=127.3.2.1:53 127.0.0.1:0`.
- when configuring resolved we prefer a 127.0.0.1 bind address, if one is configured, rather than 127.3.2.1.

On the Fedora packages we currently alter the default listener to 127.0.0.1:953 because, at the time I made the package, 127.3.2.1 was timing out—very likely because of this same issue, but I didn't dig into it at the time.  For Fedora that's okay, because it always uses systemd-resolved, but as a default for all linux that doesn't work because resolv.conf simply does not support specifying a port.  Thus we realistically still need the 127.3.2.1 listener (we avoid 127.0.0.1:53 because that is highly prone to conflicts with other daemons).

**Comment by majestrate** [comment]
this will be in the 0.9.10 tag as that is for clients after hf19, currently fixed via #1888
