### ISSUE TITLE
Unable to Change exit node as the config overrides.ini is read only

### ISSUE THREAD

**Issue by GrahamboJangles** [oxen-io/lokinet#1900]
**Describe the bug**
C:\ProgramData\lokinet\conf.d\overrides.ini is read-only by default on Windows. I had to take ownership of the file and give myself permission to write before I could change the exit node.

**To Reproduce**
1. Install Lokinet on Windows
2. Try to change the exit node

**Device and Operating system (please complete the following information):**
 - OS: Windows 10
-  Device: PC
 - Lokinet Version number or Git commit hash: lokinet-0.9.8-f702aacc

**Comment by majestrate** [comment]
windows runs as a system service as admin and because window's fs permissions are bonk normal users will by default not have read/write access to it. all of the annoying of the windows gui should be fixed in the 0.9.9 tag we'll be pushing out. you can try a nightly build [here]( https://oxen.rocks/oxen-io/lokinet/dev/?C=M&O=D)

**Comment by majestrate** [comment]
(we fixed the windows nightmare yesterday)

**Comment by GrahamboJangles** [comment]
> windows runs as a system service as admin and because window's fs permissions are bonk normal users will by default not have read/write access to it. all of the annoying of the windows gui should be fixed in the 0.9.9 tag we'll be pushing out. you can try a nightly build [here](https://oxen.rocks/oxen-io/lokinet/dev/?C=M&O=D)

Sounds good I'll give that nightly build a try

EDIT: Yep works good
