### ISSUE TITLE
lokinet ios version

### ISSUE THREAD

**Issue by tencentemr** [oxen-io/lokinet#1913]
Can anybody create a ios version of Lokinet?

**Comment by majestrate** [comment]
On Tue, 10 May 2022 07:20:38 -0700
mirinda ***@***.***> wrote:

> Can anybody create a ios version of Lokinet?
> 

you can, we won't anytime soon. apple is signaling the end of custom
vpn protocols on iphone is a very real possibility. also iphone is the
least secure platform as it has a uniform attack surface and i do not
want to lie to users about the security properties of their device.
also code signing is a pain. also lokient is gpl3 and because of the
apple app store, distribution via their app store is not compatible with
gpl3. i can keep going, but a full lokinet on ios is very unlikely
unless apple changes their direction. they wont as they dont care as
long as people buy the new iphone.

**Comment by tencentemr** [comment]
ok,got it.
