### ISSUE TITLE
lokinet-vpn does not work with ipc sockets + ipc by default

### ISSUE THREAD

**Issue by majestrate** [oxen-io/lokinet#2057]
when lokinet uses an ipc socket and we have the ability to access it just fine

`/usr/bin/lokinet-vpn --rpc ipc:///var/lib/lokinet/rpc.sock --down`

prints `std::bad_cast` and exits with status 2, instead of calling the rpc endpoint it needed to.

**Comment by jagerman** [comment]
Additionally, we should make lokinet listen on the `rpc.sock` IPC socket by default.

**Comment by dr7ana** [comment]
I believe @majestrate original bug is fixed by the CLI refactor and subsequent logic fixes as documented below (pending reproduction by others). Assuming that's confirmed, can get started on @jagerman default IPC socket listening enhancement (Note: #2110 tracks this specific enhancement)

## Reproduced Error

oxen/lokinet dev branch commit [bf0dc52df7c05d4a14b5d5140615c1d547430055](https://github.com/oxen-io/lokinet/tree/bf0dc52df7c05d4a14b5d5140615c1d547430055)

### Lokinet:

`lokinet --config /home/dan/tmp/rpc.sock`

![Screenshot from 2023-01-09 15-17-15](https://user-images.githubusercontent.com/56026339/211427396-f280cf79-87ee-4677-b1d7-a0e643c9123b.png)

### Lokinet-vpn
![Screenshot from 2023-01-09 15-17-11](https://user-images.githubusercontent.com/56026339/211427391-f41e3f97-2bc0-4080-9eb8-21a198db1dbc.png)

## Working Functionality

drouhana/lokinet cli-refactor branch commit [26beebca97d66a87d4cb8f5b67d44b242c0e7797](https://github.com/drouhana/lokinet/tree/26beebca97d66a87d4cb8f5b67d44b242c0e7797)

Note: oxen/lokinet dev branch latest commit includes the CLI refactor code in the above commit

### Lokinet

(identical command as above)
![Screenshot from 2023-01-09 15-27-06](https://user-images.githubusercontent.com/56026339/211428757-5f5fff65-c00d-4203-879f-85e074a28475.png)

### Lokinet-vpn

![Screenshot from 2023-01-09 15-27-14](https://user-images.githubusercontent.com/56026339/211428760-61f7a001-c239-4bbb-9a70-04ba4898c84b.png)
