### ISSUE TITLE
document how to do proper firewall on linux

### ISSUE THREAD

**Issue by FU3X** [oxen-io/lokinet#2154]
as another post said we need to have iptables rules for the lokinet vpn to prevent leaks. have it placed into the docs. this vpn is trash without security, and also is there any official way to automatically connect to the vpn at all times?

**Comment by majestrate** [comment]
On Wed, 05 Apr 2023 20:06:19 -0700
FU3X ***@***.***> wrote:

> as another post said we need to have iptables rules for the lokinet
> vpn to prevent leaks. have it placed into the docs. 

there is one open issue which is that we dont persist the tun
interface across restarts, which makes writting firewall rules a bit
tricky.

persisting the interface is an easy fix that has been in my backlog for
a while that i can chug out today.

it took a while but after going to the australia office i think i
sorted the issues about getting the docs repo updated so the official
site for docs will get updated much sooner now.

> this vpn is trash without security.

it depends on your threat model, lokinet is meant to run on a soho
router at it's core and thus everyone is reimplementing a set of rules
infinite numbers of times instead of just once on an image of a network
appliance that you'd audit, compile, sign, flash and then run on your
own hardware. i want to get that to as a first class mode of operation
instead of the platform support nightmare we have now but people have...
opinions.

> is there any official way to automatically
> connect to the vpn at all times?

if you specify the exit using a config file it will add it on start
up. this is the ideomatic way of configuring an exit, using the cli
tool is not recommended right now, we are going to redefine all our ZMQ
api points in the near future to make online configuration easier.

you can add config overrides into [datadir]/conf.d/ directory as *.ini
files and they are loaded in lexigraphical order. [datadir] is
overrided with the -d flag on runtime and will currently default to
$HOME/.lokinet if run as normal user and /var/lib/lokinet if run as a
privileged user (root). please keep in mind, process management is the
responsibility of the system layer not lokinet so if your process dies
it stays dead unless restarted.





-- 
~jeff

**Comment by majestrate** [comment]
On Thu, 06 Apr 2023 10:17:40 -0700
FU3X ***@***.***> wrote:

> > there is one open issue which is that we dont persist the tun
> > interface across restarts, which makes writting firewall rules a
> > bit tricky. persisting the interface is an easy fix that has been
> > in my backlog for a while that i can chug out today. it took a
> > while but after going to the australia office i think i sorted the
> > issues about getting the docs repo updated so the official site for
> > docs will get updated much sooner now.
> 
> do you have iptables rules already in place that you can keep in a
> public conf repo? I need a way for all communication protocols to be
> airtight and anonymous with performance, and for anything that
> Lokinet doesn't support to be redirected and forced through the
> network.

this isnt tor, we use the routing table to force traffic over the
lokinet network interface. a firewall should never be needed as that
means you CAN leak. when it's done via the routing table it CANT leak.

this is a fundamental concept in lokinet that sets it apart in how it
is "supposed" to be used.

> > if you specify the exit using a config file it will add it on start
> > up. this is the ideomatic way of configuring an exit, using the cli
> > tool is not recommended right now, we are going to redefine all our
> > ZMQ api points in the near future to make online configuration
> > easier.
> 
> when i use the gui it says something along the line of Loki.exit and
> i believe it chooses a exit node for you, is there a default option
> similar to that, that auto chooses the best on cli? or a "default"
> exit node?
> 

we "suggest" an exit node in some of the GUIs but i REALLY REALLY HATE
that we do. I do not want to suggest anything like that i want to let
the user decide what is right for their threat model. this year's
roadmap item is service discovery, initially meant for exit nodes which
will address this.

we do not have a default for them as there exists no sane default, by
definition.

-- 
~jeff

**Comment by majestrate** [comment]
On Sat, 08 Apr 2023 00:31:42 -0700
Frank ***@***.***> wrote:

> @FU3X FU3X  @majestrate majestrate
> >sorted the issues about getting the docs repo updated so the official
> site for docs will get updated much sooner now.
> 
> *Hey is this correct?*
> I did try Lokinet many months ago but really would like to do some
> testing. Was planning on trying Lokinet on [Qubes following this
> guide](https://privsec.dev/posts/qubes/using-lokinet-on-qubes-os/).
> From what I remember is you want to enable to systemd service so it
> starts on boot and to enable ExitNodes, first you put them in:
> `/var/lib/lokinet/lokinet.ini` after line `exit-node=` and every boot
> it will use the one set. 

yes, that is correct.

> Also remember settting like 4 or 5 hops is
> this documented? (can't find it anymore). Many people I have tried to
> get to try Lokinet were confused about documentation. From what I
> have found the GitHub repo has better then the site documentation.

it is as "documented" as every other option in the auto generated
config file, network section, hops=N with N having maximum value of 8
minimum of 2. like with RPC we should autogenerate pages for
api.oxen.io, i'll make a github issue for that.

> 
> Also is it correct understanding or fair enough to say that ExitNodes
> are similair implementation of *I2P outproxies*?

Unsure what similarities to outproxies you would refer to in this
question. Maybe? Probably.

> 
> Lastly I think it would be nice if people could set a pool of of
> their own custom list of prefered Loki *ExitNodes* in the config and
> somehow have it select a random one from their each boot.
> 

We already do that, provide multiple exit-node= values in your config.
if the comments in the auto generated config do not talk about that it
is a bug.


-- 
~jeff

**Comment by majestrate** [comment]
made #2155

**Comment by FU3X** [comment]
> made #2155

in simple terms there will be a documented kill switch method right? when do you think this will happen?

**Comment by majestrate** [comment]
On Sat, 08 Apr 2023 09:25:56 -0700
FU3X ***@***.***> wrote:

> > made #2155
> 
> in simple terms there will be a documented kill switch method right?

yes

> when do you think this will happen?
> 

when #2140 is fixed as that is what this documentation would depend on.



-- 
~jeff

**Comment by majestrate** [comment]
i think this is a duplicate of #2152 , closing in favor of that.
