### ISSUE TITLE
Doesn't connect to the internet

### ISSUE THREAD

**Issue by qdhj** [oxen-io/lokinet#2209]
My Lokinet ain't working. On pinging a website I get this error:
> Ping request could not find host ....

The Lokinet itself is working fully well though and even having some data exchange in "chart" window.

![image](https://github.com/oxen-io/lokinet/assets/122599546/e1b1fc7c-92f0-4aa1-8475-baf6c51fdca9)

What could I do?

**Device and Operating system (please complete the following information):**
 - OS: Win10
 -  Device: PC
 - Lokinet Version number or Git commit hash: lokinet-0.9.11-release

**Comment by rjc3rd** [comment]
https://github.com/oxen-io/lokinet/discussions/2208

I posted yesterday in Discussions about this too. I'm on Linux Mint with same problem.

I've also tried to make it work on Ubuntu and Windows 11. None are working for exit nodes.

Hopefully we get answers here.

**Comment by qdhj** [comment]
> #2208
> 
> I posted yesterday in Discussions about this too. I'm on Linux Mint with same problem.
> 
> I've also tried to make it work on Ubuntu and Windows 11. None are working for exit nodes.
> 
> Hopefully we get answers here.

got my problem kinda solved by checking new and new nodes. finally found one, which is working, but so slowly that it is impossible to use it. i don't know if i am doing something wrong or if it's just the lokinet so slow. you can buy loki exit node for 1$ here and check if it helps (i have no money bruh): https://www.privacyproshop.com/product/lokinet-exit-node-access-code-60-day/

**Comment by rjc3rd** [comment]
Yes I also believe it is just over loaded free exit nodes. The problem with paying for exit nodes, removes the privacy that Lokinet offers. I guess a user could pay with Monero, but I don't have Monero. From my understanding Monero is most likely the safest privacy crypto, so I should look into it.

**Comment by rjc3rd** [comment]
https://github.com/oxen-io/lokinet/discussions/2208#discussioncomment-7218566

I purchased an exit node.

Still not working for me.

**Comment by rjc3rd** [comment]
https://github.com/oxen-io/lokinet/discussions/2208#discussioncomment-7218623

I rebooted my computer to make sure there was no conflict in ram and such.

It worked. I marked my Discussion Answered.

I no longer think it's a bug. It must be the free node is just too busy.

I'm going to keep my thread updated if anything changes.

**Comment by rjc3rd** [comment]
https://github.com/oxen-io/lokinet/discussions/2208#discussioncomment-7234790

It didn't last very long. Not working again.

**Comment by ProximaNova** [comment]
> #2208
> I'm on Linux Mint with same problem.

Did you get the binary, or compile Lokinet? I am also running Linux Mint ("uname -p" = "x86_64"); I was unable to get the binary, so I successfully compiled it following these instructions: https://github.com/oxen-io/lokinet/blob/dev/docs/install.md . However, now I have various problems: no lokinet.service ("systemctl status lokinet"); cannot ping exit.loki or euroexit.loki even after adding "nameserver 127.3.2.1" to "/etc/resolv.conf" and running "lokinet &"; and various warning-tagged lines in the log of "lokinet &". (I could go into more detail on the previous text.) Lokinet worked better on Ubuntu, but I wish it also worked on Linux Mint 21.1 (vera).

Update 1: don't know why my build/compilation on Linux Mint didn't have that .service file, but here is "/lib/systemd/system/lokinet.service" from Ubuntu:
https://ipfs.io/ipfs/bafybeif2zlgjkn2kjyjxayxyvrsckqw4l7oz6uht2ipbyviiwwortzrch4

**Comment by ProximaNova** [comment]
Update 2...
- Negative: I copied /lib/systemd/system/lokinet.service from Ubuntu to the same path in Linux Mint. I then modified the text file, pasted different paths to match with Linux Mint files and folders. However, it still did not work as a daemon at all ("sudo systemctl [start/restart] lokinet").
- Positive: I ran "sudo setcap all=+eip /path/to/lokinet" which enabled lokinet to create a network interface (run "ifconfig"). I don't think it could make any network interface before (now it makes "lokitun0"). After running "lokinet 1>/dev/null 2>/dev/null &" I can successfully ping and curl nemo.loki ( http://rtuxk1ikpad3djinfuyoidoyp8q5sbi93ae4rxiymyb3ucx3bbyy.loki ).
- Negative: could not ping or curl 4 exits nodes. These ones: http://exit.loki , http://exit2.loki , http://euroexit.loki , and http://door.loki .

**Comment by I-I-IT** [comment]
A few weeks ago it didn't work. After a PC reset and a few weeks I decided to give it a new try. Still doesn`t work. The biggest problem is that it says it is connected but internet is not working. I am on Windows 11.

**Comment by NiKola-UE** [comment]
Me and my friend are both using Windows 11 and we also have the same problem that persists until we restart the computer. I understand that the exit nodes need to be set up and configured manually, but I don't know how - I'm not a programmer and have no experience with developing. 
Although this can be discussed separately (it is possible that there are already various issues and discussions on this topic), I think that some additional tools and plugins should be incorporated into the application itself in order to make it as adaptable, accessible and easy to use as possible, regardless to the operating system. There is really no need for a special browser, but whichever browser is used, it should still be specially set up to be used with Lokinet, preferably with specifical extensions, because you can never know for sure how much the browser you are using violates your privacy and collects who knows what all data. Therefore, it would not be enough to just open the browser, but it should be added to Lokinet and somehow integrated with that browser what I2P(D), Freenet/Hyphanet, Yggdrasil, ZeroNetX, and other similar networks and protocols already have, but more on that elsewhere. In any case, Lokinet is still not so easy to use for this visible surface internet and it needs to be worked on even more thoroughly.

**Comment by Ashthetik** [comment]
For everyone wondering:
The public exit nodes are basically completely full in terms of usage, so you'd need to rent/run a private exit node. Loki itself runs with, typically, minimal issues when connected to an exit that isn't under heavy use with plenty of bandwidth.

*All views and opinions are my own and are in no way influenced or conditioned by Oxen or any subsidiaries. I am not liable for any damages that may arise from my perspectives.

**Comment by NiKola-UE** [comment]
I understand what you mean, but it looks like it's technically demanding and it won't be easy for beginners to get a handle on because using Lokinet itself means you have to run your own relays, ie. nodes, which is another difference versus Tor. And does it only apply to exit nodes? You need to enter the AUTH code, but what does it represent and how to find it? 





As I said, there are still many things that need to be done. Browsers need to be adjusted and additionally configured, because how else can you find specific .loki sites on Lokinet's network, search engines that can locate them, lists with such sites, etc.?

**Comment by I-I-IT** [comment]
This project hasn't had any activity since August 2023 (the last PR  was on August 10, 2023). This means that there are probably unfixed vulnerabilities. I will advise against using this. Even on social media on our website, there hasn't been any update since early autumn 2023.

Don't believe anyone who say otherwise because they hold Session or Oxen tokens.

**Comment by NiKola-UE** [comment]
Aww, that's a real shame! I know it's hard, but if Lokinet stops developing, it will definitely be one of the worse news. I have no doubt that a lot has been invested in this project and it should not be allowed to shut down, as was the case with eg. ZeroNet, who now is discontinued.

**Comment by jagerman** [comment]
> This project hasn't had any activity since August 2023 (the last PR was on August 10, 2023). This means that there are probably unfixed vulnerabilities. I will advise against using this. Even on social media on our website, there hasn't been any update since early autumn 2023.

This is false.

Development is currently happening here: https://github.com/oxen-io/lokinet/pull/2232 and https://github.com/dr7ana/lokinet/tree/client-refactor-wip with a drastic rewrite of the communication internals (replacing it with a QUIC-based protocol) to address various network communication bugs and issues in the current implementation.  That has been a massive undertaking, aimed at delivering massive reliability and performance improvements.

> Don't believe anyone who say otherwise because they hold Session or Oxen tokens.

Or perhaps don't believe people that don't bother to look at current development before commenting.

**Comment by I-I-IT** [comment]
> Development is currently happening here: https://github.com/oxen-io/lokinet/pull/2232 and https://github.com/dr7ana/lokinet/tree/client-refactor-wip with a drastic rewrite of the communication internals (replacing it with a QUIC-based protocol) to address various network communication bugs and issues in the current implementation.

Why is this repo owned by "dr7ana" , and not Oxen-io? Why hasn't there been any update on social networks since 2023 ?

Even if this repo is legit, two things remain true 
1) **Only 1 person is working on Lokinet**. This brings enormous potential for error (since no one checks what she does) , not to talk about targeted attacks.
2) **Users most likely use a 2022 version** of Lokinet. Indeed, the latest [release](https://github.com/oxen-io/lokinet/releases) on GitHub was in Nov 2022. 
And while [Edge builds ](https://oxen.rocks/oxen-io/lokinet/) are more recent, there is a warning that 
> **Builds from this server may** work, may fail, may **wipe your hard drive without asking**, and are entirely unsupported.

**Comment by NiKola-UE** [comment]
It's good if there are updates, but it can be confusing if the same application is published in several places in parallel, regardless of the fact that Lokinet is decentralized as such, especially since nothing has been published yet on the "dr7ana/lokinet/" page under the "Releases" section. 











Also, Session is still being updated as the latest version was released in May this year, which is very good. It could be that the authors focused more on the Session than the Lokinet itself, which is understandable since neither is easy to maintain. But that requires a larger team of good and quality collaborators and other volunteers, which is even harder to find.

**Comment by jagerman** [comment]
> It's good if there are updates, but it can be confusing if the same application is published in several places in parallel, regardless of the fact that Lokinet is decentralized as such.

It is not being published in individual repositories; if you look at *all* of our software, individual work occurs in individual branch forks which gets PRed to the main repository and reviewed as part of that process by multiple devs.  The comments above were claiming no development being done, which was blatantly false: it is under heavy development, but is not yet ready for a release.

**Comment by NiKola-UE** [comment]
If I clear understand, Oxen.io and Dr7ana share some common repositories.

**Comment by I-I-IT** [comment]
>it is under heavy development, but is not yet ready for a release.

How can it be under heavy development if only one person is working on it?

>Also, Session is still being updated as the latest version was released in May this year, which is very good. It could be that the authors focused more on the Session than the Lokinet itself, which is understandable since neither is easy to maintain.

No, it's not understandable.. If you can't maintain a project, you should drop it because right now we have a project that hasn't seen any stable binaries update since 2022, so that's  unacceptable.

**Anyway, if any of you want to use a project that is thoroughly unnderfunded**, that **hasn't had** a **recent** (or even a single?) security **audit** and that has probably already been hacked by hackers, because it hasn't been updated and there has been **no proactive security measures from Oxen.IO** (such as automated vulnerabilities scanning or OSV), then you **feel free to use it, but don't complain if there is any problem in the future.**

**Comment by NiKola-UE** [comment]
I have already said that more serious development requires a larger team of collaborators and other volunteers, but it is a completely different problem if the work on the main application itself is neglected, which I do not claim has been done. If there are so many bugs and security errors (I'm not a developer), then the problem is much more serious and bigger than what this issue addresses.

**Comment by Ashthetik** [comment]
>  that **hasn't had** a **recent** (or even a single?) security **audit** and that has probably already been hacked by hackers, because it hasn't been updated and there has been **no proactive security measures from Oxen.IO** (such as automated vulnerabilities scanning or OSV), then you **feel free to use it, but don't complain if there is any problem in the future.**

Stepping in here as a community member and security analyst for other companies.

I'd like to first advise: I am in no way related to Oxen.IO, it's developers, or any party/shareholders/etc., or bound to anyone in any way. 

I can safely assure you that you cannot back this statement, as you evidentially don't know the internals of their development process; nor do I, but it's obvious that security and privacy are high priority.

As for the blind idea that it's "[...] possibly already been hacked [...]" This is quite far-fetched. While, yes, Loki and Session *do* have multiple moving parts in their *current* system(s), I personally haven't seen abusable exploits that fall outside of a single node being poorly configured or a potential "leak" of metadata that isn't already warned to avoid utilising to begin with; as it falls outside of Lokinet's current control (you can see such a warning on Session's settings panel). 

There's also countless of PRs by more than just Dr7ana, which includes Majestrate and community members, which also target security and stability issues; not to mention users like myself that quietly overlook current code states of releases –and how it functions on a live production system– to help identify bugs and other security issues the team isn't already aware of.

Although, yes, the team appears to be small, if you looked further than just what CI/CL setups that they have **public** it's more than evident security was already thought of ahead of time. As was already stated by Oxen staff: Lokinet is under complete reconstruction. Any allegations that "it's not being worked on" is purely false. Rewrites are not cheap nor quick.

Again, I'd like to reiterate that I'm in no way associated with any party here other than myself, and all observations and opinions are my own.

I'd like to further add that Lokinet has proven itself to be indefinitely harder to track and break over its alternative services such as Tor, which has a tracking and deanonymisable accuracy of >80%

**Comment by NiKola-UE** [comment]
Dear @Ashthetik, thank you for the very good, coherent and precise comment. Crackers (that's the right term to use) may be able to usurp more nodes, but I don't believe they can seriously damage the entire network because it's decentralized. But even without that, updates and patches are simply necessary, preferably as often and as much as possible for even greater security, privacy and stability. If the team is really working on the reconstruction, it is to be commended. Tor's team is slowly, but surely becoming aware of its vulnerability and invulnerability, so it needs a much more serious reconstruction, but these are some other things that there is no point in writing about here. But the topic of this issue is about the problem of connecting to the Internet and configuring the nodes properly, clarifying what the AUTH code is and whether it requires more technical knowledge to set them up, which I do not have.

**Comment by Ashthetik** [comment]
I must have missed the auth code section. Basically, that code is for private exit nodes to prevent unwanted "guests" from utilising the node without permission.

Currently, from what I can tell, the public nodes are basically maxed out, but they don't need an auth code to connect to. If you were to rent an exit node, they seller will send you the node address + auth code so you can connect to it, otherwise all public nodes (afaik there's only one or two right now) don't require the auth code.

**Comment by NiKola-UE** [comment]
Thank you. But I have the problem that after connecting, I simply cannot access any website, i.e. I cannot use the Internet at all, as if it is not working for me and this continues until I restart the computer. I really don't know why this is happening and I don't know anyone who can help me for this.

**Comment by Ashthetik** [comment]
I've already said why? All public exit nodes seem to be under heavy usage/maxed out.

**Comment by NiKola-UE** [comment]
Yes, that is completely clear to me. But how to solve it, ie. is it necessary to have some knowledge of programming or something similar? If it is necessary, I hope that it will change after the reconstruction, because we are not all so advanced users with good technical knowledge.

**Comment by Ashthetik** [comment]
> For everyone wondering:
> The public exit nodes are basically completely full in terms of usage, so you'd need to rent/run a private exit node. Loki itself runs with, typically, minimal issues when connected to an exit that isn't under heavy use with plenty of bandwidth.
> 
> *All views and opinions are my own and are in no way influenced or conditioned by Oxen or any subsidiaries. I am not liable for any damages that may arise from my perspectives.

I said what to do here, already, in this very issue thread lol
> so you'd need to rent/run a private exit node

**Comment by NiKola-UE** [comment]
I understand all that, but again, the question remains how to do it and how difficult it is.

**Comment by Ashthetik** [comment]
You can find a suggestion for it in this Discussion (https://github.com/oxen-io/lokinet/discussions/2208), or by Googling it

**Comment by NiKola-UE** [comment]
Does this mean that even us beginners can do this, or that it is actually not as complicated as it looks?

**Comment by Ashthetik** [comment]
Sorry about the delay, but yeah, it's pretty simple to work with. Lokinet only gets complicated when you start working with the more intricate pieces that are listed in their documentation

**Comment by NiKola-UE** [comment]
Yes, everything is clear to me. But who knows what the reconstruction will change everything, and hope should not be lost because Lokinet will continue to develop, which is good.

**Comment by Ashthetik** [comment]
Well if that's all cleared up, I'll summarise the issue response for everyone here and future readers:

Currently all public exit nodes are "dead" (no external access to Internet) or overloaded, please refer to https://github.com/oxen-io/lokinet/discussions/2208 for possible work arounds. In the meantime, Oxen's team are working on refactoring/reworking u bare with them while they work on it and keep patience; Lokinet isn't dead, just under heavy rework.

cc: @ProximaNova @I-I-IT @rjc3rd @qdhj

**Comment by NiKola-UE** [comment]
That would be all. For me, this issue is closed and I have nothing more to ask. Lokinet is not dead - this is all nonsense, although, I repeat, it is not easy to understand for all. It remains only for the author @qdhj to close this issue if has nothing more to say.

**Comment by uslanozan** [comment]
Guys I cannot connect Lokinet VPN Mode. I use Win 11 Home edition and tried everything to connect. I installed YogaDNS, add Cloudflare DNS settings and rule for .loki by that reference https://www.youtube.com/watch?v=eG3cbB4719o. Could you help me ?

I readed discussion but is there only one solution (buying private node)?

**Comment by Ashthetik** [comment]
As of now, yes that's the only workaround for VPN Mode. Otherwise it will only talk to whatever is within the Loki network only

**Comment by uslanozan** [comment]
Thanks a lot mate, I hope Lokinet will be better

**Comment by I-I-IT** [comment]
@dr7ana maybe you could actually answer why Lokinet isn't working for many people, instead of juste saying it's a non issue, or that this is "stupid"?

**Comment by Ashthetik** [comment]
@I-I-IT it was answered above already
