### ISSUE TITLE
end of development?

### ISSUE THREAD

**Issue by resession** [oxen-io/lokinet#2230]
no updates or commits for lokinet, is this end of development?

**Comment by Sam8688** [comment]
I was thinking the same thing about Session! When are they going to release a new version? It's been a long time.

**Comment by dr7ana** [comment]
@resession @tashijayla 
work is ongoing on re-designing and re-implementing lokinet from the service node layer upwards
https://github.com/oxen-io/lokinet/pull/2212

**Comment by jagerman** [comment]
Lokinet (and Session) are both under heavy, active development.

For Lokinet, in particular, there is a deep ongoing rewrite of the communication layer which has been a thorn in the side of Lokinet reliability and performance for years now.  This started last year with development of a dedicated communication library, https://github.com/oxen-io/oxen-libquic which has been built first and foremost for Lokinet, but will also find future uses in Session and service nodes; and has continued with updating Lokinet to use this new communication library alongside various fixes and cleaning of the Lokinet codebase to improve it's performance, reliability, and maintainability.

Unfortunately such a rewrite has taken many months, but will have dividends in terms of Lokinet's future potential.  Frustrating as it is to not see a release in some time (for the public as well as for us, since we like to see our own work out there being used!), the changes ongoing—being tracked in totality in #2212, though this is happening through many PRs—will be a major improvement to Lokinet, both for direct users of Lokinet and indirect ones (such as future Session clients that will incorporate embedded Lokinet for networking functionality).

In terms of current status, on our development testnet Lokinet routers have been up and running and communicating quickly and stably with each other since late last year, and current work is ongoing to bring Lokinet client functionality up into the new network.

**Comment by Sam8688** [comment]
> @resession @tashijayla 
> work is ongoing on re-designing and re-implementing lokinet from the service node layer upwards
> https://github.com/oxen-io/lokinet/pull/2212
> 

There have been a few small session bug fixes. It would be great to see at least those released sometime soon.

**Comment by jagerman** [comment]
We're getting off topic for a Lokinet issue, but Session has two major releases coming soon which will have both small fixes and some big improvements (to disappearing messages, and groups, specifically).
