### ISSUE TITLE
Our tentative but official roadmap issue

### ISSUE THREAD

**Issue by majestrate** [oxen-io/lokinet#224]
This is the roadmap for lokinet.

```
# previous roadmpa
0.4:  (eta end of Q1 2019)

* onion key rotation
* RC expiration

0.5: (eta end of Q2 2019)

* non stream based inter router comm protocol.

0.6:  (eta Q3 end of 2019)

* "Fully un-detectable" snapps

0.7: (eta Q4 end of 2019)

* anonymous anycast for snapps

0.x: (eta ` ‾\(._.)/‾ idk`)

* f2f connectivity layer for censor resistance
* L2 automagic peer discovery
* dht key blinding

1.0: (eta ` ‾\(._.)/‾ idk`)

* full audit
```

1.0: (end of october/november 2019)

* tooling and integration tests
* traffic prioritization
* speed up slow down link layer message
* ipv6
* finer grained logging options

**Comment by neuroscr** [comment]
Move to a file, pls

**Comment by majestrate** [comment]
updated

**Comment by neuroscr** [comment]
0.6 now scheduled to Nov
- performance
- refactors (IWP? threading?)
- loki integration testing and (alive ping)
- traffic prioritization
- fix shadow support?
- no ipv6
- no finer grained logging options
- no onion key rotation / RC expiration

(has authentication issue / SSL has a CA, this won't:
- Service nodes will communicate their RC with lokid
- lokinet clients will JSONRPC to a lokid to get RCs)

**Comment by ITwrx** [comment]
I haven't done what i would consider a deep dive on many things about blockchain technology, but i would like to try and describe what i would like to see from an application developer's POV, if you will bear with me. 

I am fairly disillusioned with the centralized web and that extends to the client/server model, in general. So, while the current capabilities of lokinet (from app hosting perspective) are a good start and better than clearnet, i don't see an anonymized client/server model as good enough/ideal, long term. However, i may write apps that use it in the interim, if that's all i, or loki, can manage for the time being.

What i would really like, and what i think would be a game changer for human freedom and loki, is **easy to use/high level, well documented** API(s) that allow application devs to create **p2p** applications that can utilize loki and lokinet, without having to worry about how everything fully works on the lower levels. I haven't looked into actually developing on eos.io due to their inaccessibility from my location due/to their business/legal approach, and lack of focus on privacy/anonymity, but i imagine what i want is what they are trying to build, but lacking the privacy/security baked in from the start, that i believe is necessary to get "all worked up" over. 

Features like:
receiving/making payments, 
finding other peers (instances of the app, instances of the app in certain app-defined groups, etc), 
secure communication between those peers/peer groups, 
shared, verified(consensus-based) state/data between those peers/groups, 
smart contracts, 
network wide, optional, multiple, portable, user IDs/profiles with reputation, (complicated, i'm sure)
and whatever else needs to be available to app devs to create unstoppable applications where every user (and/or app) is an anonymous, autonomous, client and server in charge of what data they send and receive. 
High performance for all of this, so that it's acceptable to the end users. 
Easy/high level utilization of encrypted storage nodes (i think i saw some work was planned in regards to storage nodes).
Perhaps DPoS, sub chains, and IDK_What are required for these things to be realized. 
Maybe API clients for different programming languages might be needed. I would like to write my application in nim, or maybe rust if i go back to learning that, without having to worry about c++, which i may never try to learn (or having to use FFI). 

Some/all(?) of this may already be possible, but i'm guessing it would have to be implemented on a low level, might be hacky and likely be brittle due to not being officially supported, baked-in, and unified under one design, documented, etc. IOW, i want to just worry about learning the easy api(s), and my app design and implementation, get all these features, and not have to worry about much else. :)

Thanks for reading my novel, and feel free to move my comment to it's own issue, and pick out what you find useful to move into the roadmap, or whatever you see fit. I just wanted to put this line of thought on the table, in case it could help increase the utility and attractiveness of loki and the loki network.

**Comment by majestrate** [comment]
> I haven't done what i would consider a deep dive on many things about blockchain technology, but i would like to try and describe what i would like to see from an application developer's POV, if you will bear with me.
> 
> I am fairly disillusioned with the centralized web and that extends to the client/server model, in general. So, while the current capabilities of lokinet (from app hosting perspective) are a good start and better than clearnet, i don't see an anonymized client/server model as good enough/ideal, long term. However, i may write apps that use it in the interim, if that's all i, or loki, can manage for the time being.
> 
> What i would really like, and what i think would be a game changer for human freedom and loki, is **easy to use/high level, well documented** API(s) that allow application devs to create **p2p** applications that can utilize loki and lokinet, without having to worry about how everything fully works on the lower levels. I haven't looked into actually developing on eos.io due to their inaccessibility from my location due/to their business/legal approach, and lack of focus on privacy/anonymity, but i imagine what i want is what they are trying to build, but lacking the privacy/security baked in from the start, that i believe is necessary to get "all worked up" over.
> 

right now lokinet's api (if it's even something you can call an API) is packet based connectivity triggered by DNS lookups. An additional layer atop it sounds like a fun idea but i am not sure how much of it is in the direct scope of lokinet's core.

> Features like:
> receiving/making payments,

I think the loki-core wallet should get lokinet integration soon if I have anything to say about it.

> finding other peers (instances of the app, instances of the app in certain app-defined groups, etc),

peer discovery is a subset of network bootstrap problem that does have a known solution, bootstrapping a network itself does not have many good solutions right now. I was exploring using IP multicast groups as a way to bootstrap p2p networks on top of lokinet but such is a big endeavor. I can see bootstrap/peer discovery over lokinet multicast being a thing, join a deterministically known multicast group, send some multicast traffic to it to discover other peers in it and have other peers discover it.

> secure communication between those peers/peer groups,

in the bag, lokinet already provides this, in fact that is all lokinet really is, a secure authenticated IP connectivity layer.

> shared, verified(consensus-based) state/data between those peers/groups,
> smart contracts,

these seem out of scope for lokinet.

> network wide, optional, multiple, portable, user IDs/profiles with reputation, (complicated, i'm sure)
> and whatever else needs to be available to app devs to create unstoppable applications where every user (and/or app) is an anonymous, autonomous, client and server in charge of what data they send and receive.

I would love to see an optional reputation system done in lokinet but i am at a loss on how to do it.

> High performance for all of this, so that it's acceptable to the end users.

lokinet is pretty fast right now. as for will it say fast? "probably" ™.

> Easy/high level utilization of encrypted storage nodes (i think i saw some work was planned in regards to storage nodes).
> Perhaps DPoS, sub chains, and IDK_What are required for these things to be realized.

> Maybe API clients for different programming languages might be needed. I would like to write my application in nim, or maybe rust if i go back to learning that, without having to worry about c++, which i may never try to learn (or having to use FFI).

the best api is one that is already implemented in your standard library, this is why i chose IP+dns as the primary interface for lokinet, it requires minimal fiddling to make stuff work from an app developer's side. you just make a tcp socket connection to `whatever.loki` port whatever and (if your dns is set right) it just works. additional application shims can be made such that you dont need to override the system resolver. the biggest challenge is embedding lokinet itself into an application. lots of stuff that remains unimplemented needs to be made to make embedding lokinet a reality. embedding lokinet is something i want to do soon.

> 
> Some/all(?) of this may already be possible, but i'm guessing it would have to be implemented on a low level, might be hacky and likely be brittle due to not being officially supported, baked-in, and unified under one design, documented, etc. IOW, i want to just worry about learning the easy api(s), and my app design and implementation, get all these features, and not have to worry about much else. :)
> 
> Thanks for reading my novel, and feel free to move my comment to it's own issue, and pick out what you find useful to move into the roadmap, or whatever you see fit. I just wanted to put this line of thought on the table, in case it could help increase the utility and attractiveness of loki and the loki network.

your feedback is appreciated.

**Comment by ITwrx** [comment]
interesting. thanks. also, i didn't even think about what sub-project i was posting these feature ideas in, so if any of them are useful, but go somewhere else i leave that to loki devs to decide.

**Comment by jagerman** [comment]
There are a couple different ways to come at this.  At Jeff points out, the IP+DNS approach is really nice from the point of view of setting up a client/server architecture: anything that can listen on an IP can listen on lokinet.

To reiterate what Jeff talked about above: one limitation the IP+DNS approach currently has is that it pretty much requires you to have lokinet running at the OS level.  For a lot of cases that is fine, but one thing I'd like to see us develop is a library version that can communication at the lokinet level entirely from within a library.  So, for example, using this the loki wallet would be able to "talk lokinet" to a lokid remote without having to have lokinet running as the OS level.  There are tradeoffs with this approach though: it requires more intrusive changes to an application (because they wouldn't be able to simply use plain old TCP or UDP), but for some applications (of which the loki wallet is an example) I think it would be quite useful.

**Comment by ITwrx** [comment]
yes, for the apps i was thinking of (commerce, school, etc), i expect that a normal computer user would not necessarily want to connect their whole computer to the loki network and need not know anything about how the network works. They would just open and use the application just like anything else they use on their computer. It's advertised that loki doesn't require a special browser/app, but i think a browser extension and desktop apps might be a better experience for some people. A browser extension might be an easier target for loki devs than trying to package the client for every distro/OS, IDK. Having both options might be nice. 
Many times i use tor instead of a vpn to look something up/surf news just because the vpn is more disruptive to my normal work flow, even with the speed difference of tor. I can see this being the case with everyone else too. "Ohh, i have to use this loki powered shopping/school app, let me not get emails for 2 hours." :) Even if loki net supports clearnet passthrough somehow, tbird likely won't catch on without a restart. They just won't want to use the loki powered stuff if they have to do anything extra.  Whether someone considers a browser extension or client app better for surfing client/server snapps for their use case, is anyone's guess, but for decentralized/p2p snapps i think a library is usually going to be better.

**Comment by ITwrx** [comment]
@majestrate regarding the optional reputation system: i suspect it would have to come after optional, portable, user/app-generated user profiles and the things a user can do to be rated on. It's possible loki could just provide the building blocks/infrastructure and the app ecosystem could develop competing reputation systems that users could adopt at will. IDK. 
One implementation of decentralized ID is supposedly https://zotlabs.org/page/zot/specs+zot6+home 
I haven't gotten around to looking at it very closely.

**Comment by unmellow** [comment]
> @majestrate regarding the optional reputation system: i suspect it would have to come after optional, portable, user/app-generated user profiles and the things a user can do to be rated on. It's possible loki could just provide the building blocks/infrastructure and the app ecosystem could develop competing reputation systems that users could adopt at will. IDK.
> One implementation of decentralized ID is supposedly https://zotlabs.org/page/zot/specs+zot6+home
> I haven't gotten around to looking at it very closely.

If you attach decentralized identity to lokinet I think it should at least optionally be connected to your session ID
logging into lokinet with session sounds nice

**Comment by majestrate** [comment]
this is waaaay old and outdated. needs to be redefined.
