### ISSUE TITLE
provide portable non root packages

### ISSUE THREAD

**Issue by nanderer** [oxen-io/lokinet#2245]
hi,

i would like to try out lokinet but i am not willing to system wide apt into it, so it would be grate if you could provide some tar.something packaged ready to run packages like tor browser dose, so i just have to extract and run them without any root access or other complicate stuff. That of cause for the gui and the cli version if possible

thx in advance

**Comment by jagerman** [comment]
For Lokinet this is fundamentally not possible: Lokinet requires a [tun device](https://en.wikipedia.org/wiki/TUN/TAP) to capture and inject tunneled traffic, and this tun device requires elevated permissions, in very much the same way as VPN software.

Unlike Tor, Lokinet is not limited to only carrying TCP traffic but rather is also capable of carrying UDP, ICMP and other types of IP traffic, and carries traffic seamlessly for everything on your system (or network, if installed on a router) without requiring applications to be aware of lokinet.  This requires a first class networking tunnel on the system.

It is possible to compile your own lokinet binary rather than using the published deb packages, but using it _still_ requires either setcap or a systemd service file to grant the needed networking capabilities, both of which still require root access to set up.

We are also working on an embedded version of Lokinet (which will be used within Session) but that is not yet complete, will be somewhat less performant, will require support within an application to function (i.e. does not deliver full system access), and will be limited to only carrying TCP stream traffic.  We may, in the future, investigate a SOCKS proxy configuration using this embedded Lokinet for applications where running a full lokinet isn't feasible, but it will always be a suboptimal experience compared to running a proper full Lokinet.

**Comment by nanderer** [comment]
than you should build a lite version that uses socks protocol or sth else i mean you dont need udp and icmp for browsing the web...

**Comment by jagerman** [comment]
> you dont need udp for browsing the web

https://en.wikipedia.org/wiki/HTTP/3

**Comment by nanderer** [comment]
even tho you need root you should provicde an easy  way to run it on non debian based systems, maybe some docker, flathub or snap package or some universal install script that would also run on rpm and arch based systems...

**Comment by jagerman** [comment]
Like https://rpm.oxen.io/ or https://aur.archlinux.org/packages/lokinet?

**Comment by nanderer** [comment]
i would think about some install.sh that writes stuff to /opt in a tar.gz with all binary's and stuff. Also way to run stuff without compiling or the hazzle extracting deb files. I mean at the github release page you got binary stuff for mac for win but not for linux, at least put the deb file there..

**Comment by nanderer** [comment]
@jagerman no it is not complete it is only an additional example i was giving, there are distros withaut apt, rpm and aur!

**Comment by jagerman** [comment]
Duplicate of #1709

**Comment by nanderer** [comment]
i can accept that, even tho i belive my issue is not a direct duplicate of that one, but its more like a dependency thing, you still could think about adding a tarball with binarys to future releases @jagerman
