### ISSUE TITLE
implement custom tun device for IOS/Android

### ISSUE THREAD

**Issue by majestrate** [oxen-io/lokinet#529]
```
[8:33 AM] notjeff(jeff): i have something special in mind for the tun stuff on android/ios that doesn't use tuntap vendored library
[8:34 AM] notjeff(jeff): because they don't have a traditional tun interface and use a custom api we need to write a glue layer that is aware of this
[8:34 AM] notjeff(jeff): android and ios require the packet io in a thread owned by managed code
[8:34 AM] notjeff(jeff): afaict you can't do it from native
[8:34 AM] notjeff(jeff): at least on android
[8:35 AM] notjeff(jeff): so what i was going to do was implement a special tun api that sends the packets to a pipe and then the application handles it on their side
[8:35 AM] notjeff(jeff): see llarp_ev_pkt_pipe
[8:35 AM] notjeff(jeff): that is what it is for
```

**Comment by majestrate** [comment]
because the tun interface's descriptor needs to be managed by the event loop and mobile can't do that (it seems) we need to use a pipe.

**Comment by liilac** [comment]
Can you try explain this a bit more?  Some of this seems a little unclear, and possibly based on a misunderstanding of the mobile platforms?

> i have something special in mind for the tun stuff on android/ios that doesn't use tuntap vendored library

iOS and native macOS support do not use tuntap at all, nor a variant of it (except internally). 

Native support for these platforms interacts with an asychronous object-oriented platform API: [NetworkExtension](https://developer.apple.com/documentation/networkextension)'s [NEPacketTunnelProvider](https://developer.apple.com/documentation/networkextension/packet_tunnel_provider).

> because they don't have a traditional tun interface and use a custom api we need to write a glue layer that is aware of this

See above, and also why write a glue layer, as opposed to just dispatching events from/to the llarp event queue?  The platform APIs just need to be able to receive and dispatch packet events.

> android and ios require the packet io in a thread owned by managed code

For iOS and macOS, why? Not sure about Android off the top of my head, but iOS and macOS don't have this requirement unless I'm missing something; packet IO can occur in any thread, see [NEPacketTunnelFlow](https://developer.apple.com/documentation/networkextension/nepackettunnelflow).

> afaict you can't do it from native

Do what from native? The packet processing as handled by the lokinet C++ code can occur however; it's a separate concern decoupled from the native APIs exposed by those platforms. It can run in its own thread, or however else.

> so what i was going to do was implement a special tun api that sends the packets to a pipe and then the application handles it on their side
see llarp_ev_pkt_pipe
that is what it is for

Why implement a "special tun api", instead of interacting directly with the `ev`/`ev_kqueue` queue? The relevant platform APIs are in terms of an async event queue, and map quite well to the `ev` queue. 

Writing a tun-like glue layer would be an unnecessary abstraction to present these platforms in terms of Linux/BSD-like support.

**Comment by majestrate** [comment]
>Why implement a "special tun api", instead of interacting directly with the ev/ev_kqueue queue? The relevant platform APIs are in terms of an async event queue, and map quite well to the ev queue.

the mobile platform api doesn't seem to have a way to own a file descriptor to poll which is required for adding it to the event loop, they manage their own event loop.

**Comment by majestrate** [comment]
this is done.
